name: CD

on:
  push:
    branches:
    - master
    - support/*
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - '.editorconfig'
    - '.gitattributes'
    - '.gitignore'
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/pull_request_template.md'

defaults: *default-defaults

jobs:
  build-and-test:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet6
    - *setup-verlite
    - *setup-openssl
    - *restore
    - *build
    - *test
    - *pack
    - *publish-codecov
    - *upload-artifacts
  mutation-tests:
    name: 'Mutation Test'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet6
    - *setup-verlite
    - *setup-openssl
    - *mutation-test
    - *mutation-test-archive
    - *mutation-test-upload-artifacts
  publish:
    name: 'Publish'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet6
    - *setup-openssl
    - *setup-nuget
    - *download-artifacts
    - *publish-github
